package: api
output: server.gen.go
output-options:
  skip-prune: true
generate:
  models: true
  std-http-server: true
import-mapping:
  ./models.yaml: "github.com/7yrionLannister/golang-technical-assesment-v2/internal/interface/api/model"
